feat: modify yaml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,37 +16,67 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   
-  run-test-file:
-    # The type of runner that the job will run on
-    # needs: check-test-file
-    runs-on: self-hosted
+  # run-test-file:
+  #   # The type of runner that the job will run on
+  #   # needs: check-test-file
+  #   runs-on: self-hosted
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      - name: Test Cases
-        run: |
-          g-cli --lv-ver 2020 "${{ github.workspace }}\Assignment 3\Tests\Test All.vi"
-        shell: cmd
+  #     - name: Test Cases
+  #       run: |
+  #         g-cli --lv-ver 2020 "${{ github.workspace }}\Assignment 3\Tests\Test All.vi"
+  #       shell: cmd
 
-  check-test-file:
-    # The type of runner that the job will run on
-    # needs: check-test-file
-    runs-on: self-hosted
-    # needs: run-test-file
+  # check-test-file:
+  #   # The type of runner that the job will run on
+  #   # needs: check-test-file
+  #   runs-on: self-hosted
+  #   # needs: run-test-file
     
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      - name: File not found
+  #     - name: File not found
+  #       run: |
+  #         if (failure) ; then
+  #           echo "File not found"
+  #           exit 1
+  #         else
+  #           echo "File Present"
+  #         if
+
+  Unit-tests:
+    # Use the latest version of Windows as the runner
+    runs-on: self-hosted
+
+    steps:
+      # Checkout the repository to the runner
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      # Checks if the unit test file exists
+      - name: Check if unit test project exists
+        id: check-project
         run: |
-          if (failure) ; then
-            echo "File not found"
-            exit 1
+          if [ -f "${{ github.workspace }}\Assignment 3\Tests\Test All.vi" ]; then
+            echo "::set-output name=exists::true"
+            echo "Test file found"
           else
-            echo "File Present"
-          if
+            echo "::set-output name=exists::false"
+            echo "Test file not found"
+          fi
+
+      # Run the unit test if unit test file exists
+      - name: Run tests
+        run: |
+          if [ "${{ steps.check-project.outputs.exists }}" = "true" ]; then
+            g-cli --lv-ver 2020 "${{ github.workspace }}\Assignment 3\Tests\Test All.vi"
+          else
+            echo "Unit test project file not found. Skipping tests."
+          fi
